<a href="https://colab.research.google.com/github/Shixin000/cs182-project/blob/master/interview_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Read rows and columns (cols) as integer arguments from the command line.

* Suppose I have the script in python called script.py

* And you are running the script from the terminal by passing the command line: 
  $\$python \ \ script.py \ \ 512 \ \ 128$  (suppose 512 is the number of rows, and 128 is columns)

In [102]:
# Access the command-line arguments 
import sys

arguments = sys.argv # arguments = ['script.py', '512', '128']

# Get the number of rows and columns from arguments
rows = int(arguments[1])
cols = int(arguments[2])

# 2. Create an unsigned char matrix M of size [rows x cols]

In [168]:
import numpy as np

In [169]:
#Suppose the rows and columns numbers are 256 and 128 
rows = 512
cols = 128

In [170]:
M = np.full(shape = (rows,cols),dtype=np.ubyte, fill_value=np.nan)
M

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

# 3. Fill M with randomly selected non-negative integers.

In [188]:
min = 0
max = 255*10+1

for i in range(rows):
  for j in range(cols): 
    M[i,j] = np.random.randint(min, max, dtype=int)

In [209]:
# all numbers in matrix M are unsigned char (in range 0-255)
M

array([[ 42, 153, 250, ..., 125,  63,  25],
       [196, 229, 135, ..., 172, 209,  19],
       [233,  32, 170, ..., 229, 134,  59],
       ...,
       [ 42, 214, 114, ...,  98, 115, 191],
       [204, 123, 244, ..., 172,  80,  68],
       [158, 120, 174, ...,  58,   7, 191]], dtype=uint8)

# 4,5,6. Apply the filter K=[-1, 0, 1] along the rows axis as Dx, the cols axis as Dy, and print the total time taken by the machine in computing Dx and Dy matrices.

In [210]:
import time

In [211]:
K = np.array([-1,0,1])

In [212]:
#Build the convolution function

def convo(m, k):
  """
  m : matrix with shape rows*cols
  k : the filter
  """
  rows, cols = m.shape

  # initialize the output unsigned char matrix
  D = np.full(shape = (rows,cols-len(k)+1),dtype=np.ubyte, fill_value=np.nan)

  for i in range(rows):
    for j in range(cols-len(k)+1):
      matrix_slice = m[i,j:j+3]
      D[i, j] = np.dot(matrix_slice, k)
  end = time.time()
  return D

In [226]:
start = time.time()
Dx = convo(M,K)
#To apply the filter to the cols axis, pass the transpose of the matrix M,
#then Dy will be the transpose of the output matrix
Dy = convo(M.T, K).T
end = time.time()
print(f"Runtime of computing these two matrix with shape {Dx.shape} is {end - start}")

Runtime of computing these two matrix with shape (512, 126) is 0.256819486618042


In [227]:
# all numbers in matrix Dx are unsigned char (in range 0-255)
Dx

array([[208,  53, 139, ..., 106,  33, 156],
       [195, 230, 249, ...,  55, 230, 103],
       [193, 171,  51, ...,  98,  32,  86],
       ...,
       [ 72, 183,  76, ..., 202,  18,  93],
       [ 40, 142,  92, ...,  24, 181, 152],
       [ 16,  50,  12, ..., 135,  33, 133]], dtype=uint8)

In [228]:
Dy

array([[191, 135, 176, ..., 104,  71,  34],
       [241, 118, 187, ...,  58,  46, 163],
       [249, 115,  94, ..., 247, 125, 171],
       ...,
       [ 56, 118, 136, ..., 183, 246, 181],
       [ 22,  19, 156, ..., 230, 165,  48],
       [116, 162,  60, ..., 216, 148,   0]], dtype=uint8)

# 7. Compute the min and max values for both Dx & Dy matrices individually (and in separate functions from the above computation of Dx and Dy). Print the computed min & max values.

In [231]:
Dx_max = np.max(Dx)
Dx_min = np.min(Dx)
Dx_max, Dx_min

print(f"The maximun and minimum value of matrix Dx is {Dx_max} and {Dx_min}")

The maximun and minimum value of matrix Dx is 255 and 0


In [232]:
Dy_max = np.max(Dy)
Dy_min = np.min(Dy)
Dy_max, Dy_min

print(f"The maximun and minimum value of matrix Dy is {Dy_max} and {Dy_min}")

The maximun and minimum value of matrix Dy is 255 and 0
